// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aquxtqmotbiimahboqlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdXh0cW1vdGJpaW1haGJvcWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTA1MzcsImV4cCI6MjA2MjAyNjUzN30.znxP9tr78wQPVVFVMj2BLYaVOGHRzde9X0MUnRzeoxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);